
###
GET http://localhost:8080/apikj

###

GET http://localhost:8080/api/done

###
GET http://localhost:8080/api/2

###

POST http://localhost:8080/api/p

###

DELETE http://localhost:8080/api/1

# this is the get all projects route
###
GET http://localhost:8080/api/prrojects

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "olivia-rodrigo",
  "password": "123456"
}