
###
GET http://localhost:8080/api

###

GET http://localhost:8080/api/done

###
GET http://localhost:8080/api/2

###

POST http://localhost:8080/api

###

DELETE http://localhost:8080/api/1

# this is the get all projects route
###
GET http://localhost:8080/api/projects